server:
  address: 0.0.0.0
  port: 8080
  compression:
    enabled: true
spring:
  application:
    name: rto-service
  datasource:
    url: jdbc:postgresql://localhost:5432/RTOHibernate
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_MODE:update}
    properties:
      hibernate:
        generate_statistics: true
        jdbc:
          batch_size: 4
          lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
logging.level.org.hibernate.SQL: TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE